### ISSUE TITLE
Arduino version mismatch

### ISSUE THREAD

**Issue by manuelsoldini** [zdayton/DeltaThrottle#1]
Could you please specify which arduino version are you using? It looks like your modified .cpp and .h are not compatible with my version.

**Comment by teeter477** [comment]
Manuel,

You must be mistaken as to your intended recipient, as I have absolutely no
idea what're talking about :)

**Comment by zdayton** [comment]
The version is 1.0.6. I just updated the build instructions.

**Comment by manuelsoldini** [comment]
Thank you so very much, I just migrate the code to arduino 1.6.1 and the new sparkfun code.
If I have time I'll fork this and submit a pull request so you can add support to newer versions. This thing rocks, see you on Elite,
